apiVersion: v1
kind: Service
metadata:
  name: payment
  labels:
    {{- include "payment.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "payment.selectorLabels" . | nindent 4 }}
